from .transactions import(
    SEARCH_CURRENT_USER_TRANSACTIONS,
    CALCULATE_CATEGORY_SPENDING,
    GET_CURRENT_USER_TOTAL_SPENDING,
    LIST_CURRENT_USER_CATEGORIES,
    COMPARE_CATEGORY_TO_TOTAL,
    FINISH_WITH_TRANSACTION_LIST,
    FINISH_WITH_SPENDING_SUMMARY,
    FINISH_WITH_TOTAL_SPENDING,
    FINISH_WITH_CATEGORY_LIST,
    FINISH_WITH_COMPARISON,
)

from .knowledge import (
    SEARCH_FINANCIAL_KNOWLEDGE,
    FINISH_WITH_KNOWLEDGE_ANSWER,
)

from .control import (
    FINISH_WITH_REFUSAL
)

ALL_TOOLS = [
    SEARCH_CURRENT_USER_TRANSACTIONS,
    CALCULATE_CATEGORY_SPENDING,
    GET_CURRENT_USER_TOTAL_SPENDING,
    LIST_CURRENT_USER_CATEGORIES,
    COMPARE_CATEGORY_TO_TOTAL,
    SEARCH_FINANCIAL_KNOWLEDGE,
    FINISH_WITH_TRANSACTION_LIST,
    FINISH_WITH_SPENDING_SUMMARY,
    FINISH_WITH_TOTAL_SPENDING,
    FINISH_WITH_CATEGORY_LIST,
    FINISH_WITH_COMPARISON,
    FINISH_WITH_KNOWLEDGE_ANSWER,
    FINISH_WITH_REFUSAL
]

TOOLS_BY_NAME = {tool.name: tool for tool in ALL_TOOLS}
OPENAI_TOOLS = [tool.to_openai_tool() for tool in ALL_TOOLS]
